# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:inf0puCeaI7uML4dabartAJBRDiDOp8RzgGEyrLoD5Q=,iv:WFNWOq7nt/TdDFygw6TRnVrJos6Llfgz1wD94Ykd6jI=,tag:11LbEaa2ITZDuW9KFx+cAw==,type:str]
sops:
  age:
    - recipient: age1nrck937xu2m0klx8ztnccr3qyns4sax6yqyzfnju8gxs3dvqhevqvtm6ys
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDluMFBLaU9zU1pud3Bz
        alZlQ3VLb0RhbjExdHExRWJhdENaT2c1QUMwCmZsb3VjblZtSjBGVnV6VVdjMXVX
        OEVyUkJlS0VMa0NvR3o0dm1lbmxaSXcKLS0tIFdXaE5jMnIyL01jYXRkRG5WWHdz
        Y1RtY1ZFQjRPRi8wS25rdGVuSkdKelEK2XOPo8YfngH2x2ENNFvLXi3dwyHIFOqu
        Q2w87vpWHHXKRBShTypHVHBYUMi+/g3VzDxi8arU34dkI8u+Pc7KDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-29T18:28:19Z"
  mac: ENC[AES256_GCM,data:Q3g4pBsQN413Pq7zmFK8kHJEpBeB8hDofGAj+z7VVuhhdsnItrlQMcBH/NubAqqI+9bdmwFwYptrH7UUsiY56HQsE70gxiapOrwlWI1RgmeyVvZMjIsn6cg0iMBOVYrXvskSFBXOuoNw6ZTMva9NXWesPg4lzecQEI11cE26b00=,iv:1AOTrmruH++i+9euX+z6RDvGvlghO7i+QoKEf2ZBsx8=,tag:vL9nbDxG7i5B6/WCrZgpSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
